backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  commit_messages:
    create: âœ¨ Create {{collection}} â€œ{{slug}}â€
    update: âœ¨ Update {{collection}} â€œ{{slug}}â€
    delete: ğŸ”¥ Delete {{collection}} â€œ{{slug}}â€
    uploadMedia: ğŸ–¼ Upload â€œ{{path}}â€
    deleteMedia: ğŸ”¥ Delete â€œ{{path}}â€

media_folder: "uploads/images" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "_posts/blog" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", default: "Blog", required: false}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Featured Image
            name: featured-image
            widget: image
            media_library:
              config:
                multiple: false

