backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  commit_messages:
    create: âœ¨ Create {{collection}} â€œ{{slug}}â€
    update: âœ¨ Update {{collection}} â€œ{{slug}}â€
    delete: ğŸ”¥ Delete {{collection}} â€œ{{slug}}â€
    uploadMedia: ğŸ–¼ Upload â€œ{{path}}â€
    deleteMedia: ğŸ”¥ Delete â€œ{{path}}â€

media_folder: "/src/static/images/uploads" # Folder where user uploaded files should go
public_folder: "/static/images/uploads"
# publish_mode: editorial_workflow # Editorial workflow works with GitHub repositories only.

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    preview_path_date_field: "date"
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "src/content/posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}-{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        dateformat: "YYYY-MM-DD"
        timeformat: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["post"]
        required: true
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        media_library:
          config:
            multiple: false
        required: false
      - label: "Image_caption"
        name: "image_caption"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
