backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  commit_messages:
    create: ‚ú® Create {{collection}} ‚Äú{{slug}}‚Äù
    update: ‚ú® Update {{collection}} ‚Äú{{slug}}‚Äù
    delete: üî• Delete {{collection}} ‚Äú{{slug}}‚Äù
    uploadMedia: üñº Upload ‚Äú{{path}}‚Äù
    deleteMedia: üî• Delete ‚Äú{{path}}‚Äù

media_folder: "src/static/images/uploads" # Folder where user uploaded files should go
publish_mode: editorial_workflow # Editorial workflow works with GitHub repositories only.

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "src/posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Publish Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["post"]
        required: true
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        media_library:
          config:
            multiple: false
        required: false
      - label: "Image_caption"
        name: "image_caption"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "globals"
    label: "Globals"
    files:
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/dev/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Url"
                name: "url"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "string"
                  - label: "Url"
                    name: "url"
                    widget: "string"

