backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  commit_messages:
    create: âœ¨ Create {{collection}} â€œ{{slug}}â€
    update: âœ¨ Update {{collection}} â€œ{{slug}}â€
    delete: ğŸ”¥ Delete {{collection}} â€œ{{slug}}â€
    uploadMedia: ğŸ–¼ Upload â€œ{{path}}â€
    deleteMedia: ğŸ”¥ Delete â€œ{{path}}â€

media_folder: "./src/static/images/uploads" # Folder where user uploaded files should go
publish_mode: editorial_workflow # Editorial workflow works with GitHub repositories only.

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "./src/posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - label: "Image_caption"
        name: "image_caption"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["post"]
        required: true
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mm:ss"
    meta: # Meta data fields. Just like fields, but without any preview element
      # - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

